---
title: "CART_scRNAseq"
author: "Julia Hitschfel"
date: "2025-11-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(Seurat)
library(BPCells)
library(presto)
library(glmGamPoi)
library(hdf5r)
library(SingleCellExperiment)
library(scDblFinder)
library(scRepertoire)
library(RColorBrewer)
```


```{r Load Data}
All.data <- list.dirs("/data/", recursive = F)
tp.ex <- c("/data/2024_10_15","/data/2025_04_23")
All.data.tp.ex <- setdiff(All.data, tp.ex)

list.10x <- list()
for(i in All.data.tp.ex){
  rnaseq.data <- Read10X_h5(paste0(i, "/count/sample_filtered_feature_bc_matrix.h5"))
  pbmc <- CreateSeuratObject(counts = rnaseq.data, project = "pbmc3k", min.cells = 3, 
                             min.features = 200)
  list.10x[[i]] <- pbmc
}
```

```{r Cell Counts per Sample before QC}
cell_counts_before_QC <- vector()
for(i in 1:length(list.10x)){
  cell_counts_before_QC[i] <- nrow(list.10x[[i]]@meta.data)
}
names(cell_counts_before_QC) <- substr(names(list.10x), 25, 100)
counts_before_qc <- as.data.frame(cell_counts_before_QC)
counts_before_qc
```

```{r Calculate and examine some QC metrics}
qc_plots <- list()
qc_plots_doub_rem <- list()
for(i in 1:length(list.10x)){
  scobject <- list.10x[[i]]
  scobject[["percent.mt"]] <- PercentageFeatureSet(scobject, pattern = "^MT-")
  scobject@meta.data$date <- substr(names(list.10x)[i], 25, 100)
  qc_graph <- ggplot(data = scobject@meta.data, aes(x = nCount_RNA, y = nFeature_RNA)) +
    geom_point(aes(colour = percent.mt))
  sce <- as.SingleCellExperiment(scobject)
  sce <- scDblFinder(sce, samples = sce@colData$date)
  table(sce$scDblFinder.class)
  scobject$scDBLFinder <- sce$scDblFinder.class
  scobject <- subset(scobject, scDBLFinder == "singlet")
  qc_graph_doublet_rem <- ggplot(data = scobject@meta.data, aes(x = nCount_RNA, y = nFeature_RNA)) +
    geom_point(aes(colour = percent.mt))
  scobject <- subset(scobject, subset = nFeature_RNA > 200 & percent.mt < 12.5 & nCount_RNA < 100000)
  scobject <- SCTransform(scobject, vars.to.regress = "percent.mt")
  list.10x[[i]] <- scobject
  qc_plots[[i]] <- qc_graph
  qc_plots_doub_rem[[i]] <- qc_graph_doublet_rem
}

scobject <- merge(x = list.10x[[1]], y = c(list.10x[2:length(list.10x)]))
ggplot(scobject@meta.data, aes(x = nCount_RNA, y = nFeature_RNA)) + 
  geom_point(aes(colour = percent.mt))
ggplot(scobject@meta.data, aes(x = date, y = nCount_RNA)) + geom_boxplot(outlier.color = "red")
ggplot(scobject@meta.data, aes(x = date, y = nFeature_RNA)) + geom_boxplot(outlier.color = "red")
ggplot(scobject@meta.data, aes(x = date, y = percent.mt)) + geom_boxplot(outlier.color = "red")

sum_table <- scobject@meta.data %>% group_by(date) %>% 
  summarise(RNA.count.median = median(nCount_RNA), RNA.feature.median = median(nFeature_RNA),
            MT.median = median(percent.mt))
sum_table
```


```{r Remaining cells after quality control} 
counts_after_qc <- table(scobject@meta.data$date)
cell_counts <- cbind(counts_before_qc, counts_after_qc)
cell_counts
```


```{r Clustering Analysis for all timepoints and cell types}
# Identify the 10 most highly variable genes
VariableFeatures(scobject[["SCT"]]) <- rownames(scobject[["SCT"]]@scale.data)
top10 <- head(VariableFeatures(scobject), 10)
top10

scobject <- RunPCA(scobject, features = VariableFeatures(object = scobject))

# Examine and visualize PCA results a few different ways
print(scobject[["pca"]], dims = 1:5, nfeatures = 5)
VizDimLoadings(scobject, dims = 1:2, reduction = "pca")
DimPlot(scobject, reduction = "pca") + NoLegend()

#Check some initial confounding factors on the PCA
FeaturePlot(scobject, features = "nCount_RNA", reduction = "pca") 
FeaturePlot(scobject, features = "nCount_RNA", reduction = "pca", dims = c(1,3))
FeaturePlot(scobject, features = "nFeature_RNA", reduction = "pca") 
#nFeature_RNA might have some influence on PC_1. Keep that in mind and examine further
FeaturePlot(scobject, features = "nFeature_RNA", reduction = "pca", dims = c(1,3)) 
FeaturePlot(scobject, features = "percent.mt", reduction = "pca") 
FeaturePlot(scobject, features = "percent.mt", reduction = "pca", dims = c(1,3))

DimPlot(scobject, reduction = "pca", group.by = "date", split.by = "date", ncol = 3) 

DimHeatmap(scobject, dims = 1, cells = 500, balanced = TRUE)
DimHeatmap(scobject, dims = 1:15, cells = 500, balanced = TRUE)

ElbowPlot(scobject, ndims = 25)

#Cluster the cells
scobject <- FindNeighbors(scobject, dims = 1:20)
scobject <- FindClusters(scobject, resolution = c(0.4, 0.6, 0.8))
scobject <- RunUMAP(scobject, dims = 1:20)
saveRDS(scobject, file = "seurat_SCTransform_NOT_integrated.rds")
DimPlot(scobject, reduction = "umap", label = T)
DimPlot(scobject, reduction = "umap", group.by = "SCT_snn_res.0.6", label = T)
DimPlot(scobject, reduction = "umap", group.by = "SCT_snn_res.0.4", label = T)


DimPlot(scobject, reduction = "umap", group.by = "date")
DimPlot(scobject, reduction = "umap", group.by = "date", split.by = "date", ncol = 3)
```


```{r Integration per timepoint}
scobject_int <- IntegrateLayers(object = scobject, method = CCAIntegration, 
                                normalization.method = "SCT", verbose = FALSE)

# re-join layers after integration
scobject_int[["RNA"]] <- JoinLayers(scobject_int[["RNA"]])

scobject_int <- FindNeighbors(scobject_int, reduction = "integrated.dr", dims = 1:25)
scobject_int <- FindClusters(scobject_int, resolution = c(0.4,0.6,0.8,1))
scobject_int <- RunUMAP(scobject_int, dims = 1:25, reduction = "integrated.dr")
saveRDS(scobject_int, file = "integrated_seurat.rds")
# Visualization
DimPlot(scobject_int, reduction = "umap", group.by = "date")
DimPlot(scobject_int, reduction = "umap", group.by = "date", split.by = "date", ncol = 3)

DimPlot(scobject_int, reduction = "umap", group.by = "SCT_snn_res.0.4", label = T)

DimPlot(scobject_int, reduction = "integrated.dr", group.by = "date", split.by = "date", ncol = 3)

```


```{r Examine Clusters integrated object}
Cells_per_cluster <- table(scobject_int@meta.data$SCT_snn_res.0.4)
Cells_per_cluster

scobject_int <- PrepSCTFindMarkers(scobject_int)
Idents(scobject_int) <- "SCT_snn_res.0.4"
Cluster_markers <- FindAllMarkers(scobject_int, logfc.threshold = 0.25, min.pct = 0.5, only.pos = T)
Cluster_top10_markers <- Cluster_markers %>% group_by(cluster) %>% slice_head(n = 10)
Cluster_top10_markers
write.csv(Cluster_markers, 
       file = "Cluster_marker_genes_res04_cca_integrated.csv")
```


```{r Expression RPS and RPL transcripts}
# Schauen wir uns kurz noch die ribosomalen RNAs an: 
scobject_int[["percent.rps"]] <- PercentageFeatureSet(scobject_int, pattern = "^RPS")
FeaturePlot(scobject_int, reduction = "pca", features = "percent.rps")
FeaturePlot(scobject_int, reduction = "pca", dims = c(1,3), features = "percent.rps")
FeaturePlot(scobject_int, reduction = "umap", features = "percent.rps")
FeaturePlot(scobject_int, reduction = "integrated.dr", features = "percent.rps")

VlnPlot(scobject_int, features = "percent.rps", group.by = "date")

scobject_int[["percent.rpl"]] <- PercentageFeatureSet(scobject_int, pattern = "^RPL")
FeaturePlot(scobject_int, reduction = "pca", features = "percent.rpl")
FeaturePlot(scobject_int, reduction = "pca", dims = c(1,3), features = "percent.rpl")
FeaturePlot(scobject_int, reduction = "umap", features = "percent.rpl")
FeaturePlot(scobject_int, reduction = "integrated.dr", features = "percent.rpl")


VlnPlot(scobject_int, features = "percent.rpl", group.by = "date")
```


```{r Examine weird Clusters}
VlnPlot(scobject_int, features = "nCount_RNA", group.by = "SCT_snn_res.0.4")
VlnPlot(scobject_int, features = "nFeature_RNA", group.by = "SCT_snn_res.0.4")
VlnPlot(scobject_int, features = "percent.mt", group.by = "SCT_snn_res.0.4")
```


```{r Cluster over time}
Cluster_over_time <- scobject_int@meta.data %>% group_by(date, SCT_snn_res.0.4) %>% 
  summarise(n = n()) %>% mutate(Freq = n/sum(n))

farbenblind15 <- c("#000000","#004949","#009292","#FF6DB6","#FFB6DB",
                  "#490092","#006DDB","#B66DFF","#6DB6FF","#B6DBFF",
                  "#920000","#924900","#DB6D00","#24FF24","#FFFF6D") 
palette1 <- brewer.pal(8, "Set2")  # First palette

combined_palette <- c(farbenblind15, palette1)  # Combine the palettes

ggplot(Cluster_over_time, aes(x = date, y = Freq, fill = SCT_snn_res.0.4)) + 
  geom_col(color = "black") + scale_fill_manual(values = combined_palette)

```
