---
title: "Markers_Clusters"
author: "Julia Hitschfel"
date: "2025-11-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Seurat)
library(dplyr)
library(ggplot2)
library(colorspace)
library(RColorBrewer)
```


```{r Load Data and examine resolutions}
scobject <- readRDS(file ="integrated_seurat_singleR_annotations.rds")

DimPlot(scobject, reduction='umap', group.by='SCT_snn_res.0.8', label = T)
DimPlot(scobject, reduction='umap', group.by='SCT_snn_res.0.6', label = T)
DimPlot(scobject, reduction='umap', group.by='SCT_snn_res.0.4', label = T)
DimPlot(scobject, reduction='umap', group.by='SingleR.labels', label = T) + NoLegend()
```

## T Cell Marker

```{r Main Marker genes clusters}
Idents(scobject) <- scobject$SCT_snn_res.0.4
scobject <- PrepSCTFindMarkers(scobject)
All_markers <- FindAllMarkers(scobject, logfc.threshold = 0.5, min.pct = 0.25, only.pos = T)
All_markers_top5 <- All_markers %>% group_by(cluster) %>% slice_head(n = 5)

# Marker T cells 
FeaturePlot(scobject, features = "CD3D", reduction = "umap")
FeaturePlot(scobject, features = "CD8A", reduction = "umap")
FeaturePlot(scobject, features = "CD8B", reduction = "umap")
FeaturePlot(scobject, features = "CD4", reduction = "umap")
```

## B cell Marker

```{r B cell Marker}
FeaturePlot(scobject, features = "CD19", reduction = "umap")
FeaturePlot(scobject, features = "MS4A1", reduction = "umap")
FeaturePlot(scobject, features = "MZB1", reduction = "umap")
FeaturePlot(scobject, features = "JCHAIN", reduction = "umap")
```

## Monocyten and Myeloid cells

```{r Monocyte and Myeloid Cell Marker}
FeaturePlot(scobject, features = "CD14", reduction = "umap")
FeaturePlot(scobject, features = "FCGR3A", reduction = "umap")
FeaturePlot(scobject, features = "CD80", reduction = "umap")
FeaturePlot(scobject, features = "HLA-DPA1", reduction = "umap")
FeaturePlot(scobject, features = "ITGAX", reduction = "umap")
FeaturePlot(scobject, features = "IFI30", reduction = "umap")
```


## Connective Tissue Marker 

```{r Connective tissue markers}
FeaturePlot(scobject, features = "COL3A1", reduction = "umap")
FeaturePlot(scobject, features = "COL6A2", reduction = "umap")
FeaturePlot(scobject, features = "MMP2", reduction = "umap")
FeaturePlot(scobject, features = "CXCL14", reduction = "umap")
FeaturePlot(scobject, features = "ACTA2", reduction = "umap")
FeaturePlot(scobject, features = "PDPN", reduction = "umap")
FeaturePlot(scobject, features = "LGR5", reduction = "umap")
```

## Endothelial cell Marker

```{r Endothelial cell Marker}
FeaturePlot(scobject, features = "SPARCL1", reduction = "umap")
FeaturePlot(scobject, features = "PECAM1", reduction = "umap")
FeaturePlot(scobject, features = "PLVAP", reduction = "umap")
```


## NK cell marker

```{r NK Cell Marker}
FeaturePlot(scobject, features = "NKG7", reduction = "umap")
FeaturePlot(scobject, features = "CST7", reduction = "umap")
FeaturePlot(scobject, features = "GNLY", reduction = "umap")
FeaturePlot(scobject, features = "CD3E", reduction = "umap")
```


## Epithelial cell marker

```{r Epithelzell Marker}
FeaturePlot(scobject, features = "GPX2", reduction = "umap")
FeaturePlot(scobject, features = "AGR2", reduction = "umap")
FeaturePlot(scobject, features = "LGALS4", reduction = "umap")
FeaturePlot(scobject, features = "PIGR", reduction = "umap")
FeaturePlot(scobject, features = "TSPAN1", reduction = "umap")
```


## Granulocytes/Mast Cells

```{r Granulocyte Markers}
FeaturePlot(scobject, features = "TPSB2", reduction = "umap")
FeaturePlot(scobject, features = "TPSAB1", reduction = "umap")
FeaturePlot(scobject, features = "CPA3", reduction = "umap")
```


## Missing Cluster Identities

```{r Missing Cluster}
FeaturePlot(scobject, features = "ALAS2", reduction = "umap")	
FeaturePlot(scobject, features = "HBA2", reduction = "umap")	
FeaturePlot(scobject, features = "IL32", reduction = "umap")	
FeaturePlot(scobject, features = "SPARC", reduction = "umap")
FeaturePlot(scobject, features = "SOX10", reduction = "umap")	

FeaturePlot(scobject, features = "IGHM", reduction = "umap")	
```

## T cell Marker in Colitis

```{r T Cell Clusters Associated with UC}
FeaturePlot(scobject, features = "BATF", reduction = "umap")
FeaturePlot(scobject, features = "IL26", reduction = "umap")
```


## Populationen over the course of treatment

```{r Cluster Proportions over Time new Manual Annotations}
scobject <- RenameIdents(scobject, '0' = 'Fibroblasts_1',
                         '1' = 'Intestinal Epithelial Cells_1',
                         '2' = 'T cells_1',
                         '3' = 'Fibroblasts_2', 
                         '4' = 'Distal Enterocytes', 
                         '5' = 'Myeloid Cells_1', 
                         '6' = 'T cells_2', 
                         '7' = 'Endothelial Cells', 
                         '8' = 'Secretory Epithelial Cells', 
                         '9' = 'Intestinal Epithelial Cells_2', 
                         '10' = 'Mast Cells', 
                         '11' = 'B cells', 
                         '12' = 'Myeloid Cells_2', 
                         '13' = 'Smooth Muscle Cells_1', 
                         '14' = 'Smooth Muscle Cells_2', 
                         '15' = 'Neurons', 
                         '16' = 'Intestinal Epithelial Cells_2',
                         '17' = 'Mast Cells')

scobject$Annotations.0.4 <- Idents(scobject)

saveRDS(scobject, 
        file = "integrated_seurat_refined_annotations.rds")

Cell_proportions <- scobject@meta.data %>% group_by(date, Annotations.0.4) %>% 
  summarise(n = n()) %>% mutate(Freq = n/sum(n))

write.csv(Cell_proportions, "Cell_proportions_over_time.csv")

farbenblind15 <- c("#000000","#004949","#009292","#FF6DB6","#FFB6DB",
                  "#490092","#006DDB","#B66DFF","#6DB6FF","#B6DBFF",
                  "#920000","#924900","#DB6D00","#24FF24","#FFFF6D") 

palette.2 <- brewer.pal(8, "Set2")
combined.palette <- c(farbenblind15, palette.2)

ggplot(Cell_proportions, aes(x = date, y = Freq, fill = Annotations.0.4)) + 
  geom_col(colour = "black") + labs(title = "Cell Proportions Integrated Res. 0.4") + 
  scale_fill_manual(values = combined.palette) + theme_minimal()

ggsave("Cell_proportions_time_integrated_res04.pdf",
      plot = last_plot(), width = 30, height = 20, units = "cm")
```

```{r Notable changes in cell populations}
Tcells1 <- Cell_proportions %>% filter(Annotations.0.4 == "T cells_1")
Tcells1_gg <- ggplot(Tcells1, aes(x = date, y = Freq)) + geom_col(fill = "#009292") +  
  labs(title = "T cell Frequencies")
Tcells1_gg

Fibroblasts <- Cell_proportions %>% filter(Annotations.0.4 == "Fibroblasts_1")
Fibroblasts_gg <- ggplot(Fibroblasts, aes(x = date, y = Freq)) + geom_col(fill = "#000000") + 
labs(title = "Fibroblast_1 Frequencies")
Fibroblasts_gg

Fibroblasts_2 <- Cell_proportions %>% filter(Annotations.0.4 == "Fibroblasts_2")
Fibroblasts_2_gg <- ggplot(Fibroblasts_2, aes(x = date, y = Freq)) + geom_col(fill = "#FF6DB6") + 
labs(title = "Fibroblast_2 Frequencies")
Fibroblasts_2_gg

Myeloid1 <- Cell_proportions %>% filter(Annotations.0.4 == "Myeloid Cells_1")
Myeloid1_gg <- ggplot(Myeloid1, aes(x = date, y = Freq)) + geom_col(fill = "#490092") + 
labs(title = "Myeloid Cell Frequencies")
Myeloid1_gg
  
BCells <- Cell_proportions %>% filter(Annotations.0.4 == "B cells")
BCells_gg <- ggplot(BCells, aes(x = date, y = Freq)) + geom_col(fill = "#924900") + 
labs(title = "B Cell Frequencies")
BCells_gg

Secretory <- Cell_proportions %>% filter(Annotations.0.4 == "Secretory Epithelial Cells")
Secretory_gg <- ggplot(Secretory, aes(x = date, y = Freq)) + geom_col(fill = "#6DB6FF") + 
labs(title = "Secretory Epithelial Cell Frequencies")
Secretory_gg

IECs1 <- Cell_proportions %>% filter(Annotations.0.4 == "Intestinal Epithelial Cells_1")
IECs1_gg <- ggplot(IECs1, aes(x = date, y = Freq)) + geom_col(fill = "#B6DBFF") + 
labs(title = "Intestinal Epithelial Cell 2 Frequencies")
IECs1_gg

Tcells_2 <- Cell_proportions %>% filter(Annotations.0.4 == "T cells_2")
Tcells_2_gg <- ggplot(Tcells_2, aes(x = date, y = Freq)) + geom_col(fill = "#006DDB") + 
labs(title = "T cells 2 Frequencies")
Tcells_2_gg

DisEnt <- Cell_proportions %>% filter(Annotations.0.4 == "Distal Enterocytes")
DisEnt_gg <- ggplot(DisEnt, aes(x = date, y = Freq)) + geom_col(fill = "#FFB6DB") + 
labs(title = "Distal Enterocytes Frequencies")
DisEnt_gg
```
