---
title: "T_cell_subclustering"
author: "Julia Hitschfel"
date: "2025-08-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Seurat)
library(dplyr)
library(ggplot2)
library(BPCells)
library(presto)
library(glmGamPoi)
library(hdf5r)
library(knitr)
library(pheatmap)
library(RColorBrewer)

farbenblind15 <- c("#000000","#004949","#009292","#FF6DB6","#FFB6DB",
                  "#490092","#006DDB","#B66DFF","#6DB6FF","#B6DBFF",
                  "#920000","#924900","#DB6D00","#24FF24","#FFFF6D") 

```

# T Cell Subclustering Analysis with Integration (CCA)

```{r Read in Dataset}
scobject <- readRDS("integrated_seurat_refined_annotations.rds")

Idents(scobject) <- scobject$SCT_snn_res.0.4
All_Tcells_comb <- WhichCells(scobject, idents = c(2,6,12))

APCs <- WhichCells(scobject, expression = `HLA-DQA1` > 1)
All_Tcells_filt <- setdiff(All_Tcells_comb, APCs)

FeaturePlot(scobject, features = "CD3E", cells = All_Tcells_filt, slot = "counts", max.cutoff = 3)
```


```{r Establish filters}
#Positive filter
FeaturePlot(scobject, features = "CD3D", slot = "counts", max.cutoff = 5)
FeaturePlot(scobject, features = "CD3E", slot = "counts", max.cutoff = 5)
FeaturePlot(scobject, features = "CD247", slot = "counts", max.cutoff = 5) #CD3 zeta
FeaturePlot(scobject, features = "CD2", slot = "counts", max.cutoff = 5)
FeaturePlot(scobject, features = "CD5", slot = "counts", max.cutoff = 5)
FeaturePlot(scobject, features = "PTPRC", slot = "counts", max.cutoff = 5)

#Negative filter
FeaturePlot(scobject, features = "KRT8", slot = "counts", max.cutoff = 5)

FeaturePlot(scobject, features = "CD14", slot = "counts", max.cutoff = 5)
FeaturePlot(scobject, features = "CD68", slot = "counts", max.cutoff = 5)

genes_to_filter <- c('CD3D', 'CD3E', 'CD247', 'CD2', 'CD5', 'PTPRC')
Non_Tcells <- WhichCells(scobject, expression = CD3D < 1 & CD3E < 1 & CD247 < 1 & CD2 < 1 & 
                           CD5 < 1 & PTPRC < 1, slot = "counts")

No_Tcells_Seurat <- subset(scobject, cells = Non_Tcells)

DimPlot(No_Tcells_Seurat, reduction = "umap")
```


```{r Integration and Clustering of T cell subsets}
All.data <- list.dirs("/data/", recursive = F)

list.10x <- list()
counter <- 1
for(i in All.data){
  rnaseq.data <- Read10X_h5(paste0(i, "/count/sample_filtered_feature_bc_matrix.h5"))
  pbmc <- CreateSeuratObject(counts = rnaseq.data, project = "Colitis", min.cells = 3, 
                             min.features = 200)
  pbmc <- RenameCells(pbmc, new.names = paste0(colnames(pbmc), "_", counter))
  pbmc <- subset(pbmc, cells = All_Tcells_comb)
  Tcells <- WhichCells(pbmc, expression = CD3D > 0 | CD3E > 0 | CD247 > 0|
                   CD2 > 0 |  CD5 > 0 | PTPRC > 0, slot = "counts")
  Epithelial_Cells <- WhichCells(pbmc, expression = KRT8 > 0 | KRT86 > 1, slot = "counts")
  Monocytes <- WhichCells(pbmc, expression = CD14 > 0 | CD68 > 0, slot = "counts")
  APCs <- WhichCells(pbmc, expression = `HLA-DQA1` > 1, slot = "counts")
  Tcells_filtered <- setdiff(Tcells, Epithelial_Cells)
  Tcells_filtered <- setdiff(Tcells_filtered, Monocytes)
  Tcells_filtered <- setdiff(Tcells_filtered, APCs)
  pbmc <- subset(pbmc, cells = Tcells_filtered)
  pbmc@meta.data$percent.mt <- PercentageFeatureSet(pbmc, pattern = "^MT")
  pbmc@meta.data$percent.rps <- PercentageFeatureSet(pbmc, pattern = "^RPS")
  pbmc@meta.data$percent.rpl <- PercentageFeatureSet(pbmc, pattern = "^RPL")
 
  pbmc@meta.data$date <- substr(i, 25, 100)
  pbmc <- SCTransform(pbmc, verbose = FALSE)
  list.10x[[i]] <- pbmc
  counter <- counter + 1
}

integ_features <- SelectIntegrationFeatures(object.list = list.10x, nfeatures = 3000) 
scTcells <- merge(x = list.10x[[1]], y = c(list.10x[2:length(list.10x)]), merge.data = T)
DefaultAssay(scTcells) <- "SCT"
VariableFeatures(scTcells) <- integ_features
scTcells <- RunPCA(scTcells, assay = "SCT", npcs = 50)

scTcells <- IntegrateLayers(object = scTcells, method = CCAIntegration, 
                            normalization.method = "SCT", verbose = F)
scTcells <- FindNeighbors(scTcells, reduction = "integrated.dr", dims = 1:30)
scTcells <- FindClusters(scTcells, resolution = c(0.4,0.6,0.8))

scTcells <- RunUMAP(scTcells, reduction = "integrated.dr", assay = "SCT", 
                             dims = 1:30)

DimPlot(scTcells, reduction = "umap", group.by = "SCT_snn_res.0.8", label = T, cols = farbenblind15, 
        label.size = 6)
DimPlot(scTcells, reduction = "umap", group.by = "SCT_snn_res.0.6", label = T, cols = farbenblind15,
        label.size = 6)
DimPlot(scTcells, reduction = "umap", group.by = "SCT_snn_res.0.4", label = T, cols = farbenblind15,
        label.size = 6)

DimPlot(scTcells, reduction = "umap", group.by = "date")
DimPlot(scTcells, reduction = "umap", group.by = "date", split.by = "date", ncol = 3)

```


```{r Identify Clusters}
Idents(scTcells) <- scTcells$SCT_snn_res.0.6

scTcells <- PrepSCTFindMarkers(scTcells)
Tcell_markers_06 <- FindAllMarkers(scTcells, logfc.threshold = 0.25, min.pct = 0.25, 
                                   only.pos = T)

FeaturePlot(scTcells, reduction = "umap", features = "PTPRC")
FeaturePlot(scTcells, reduction = "umap", features = "CD2")
FeaturePlot(scTcells, reduction = "umap", features = "CD5")
FeaturePlot(scTcells, reduction = "umap", features = "CD3D")
FeaturePlot(scTcells, reduction = "umap", features = "CD3E")
FeaturePlot(scTcells, reduction = "umap", features = "CD3G")
FeaturePlot(scTcells, reduction = "umap", features = "CD8A")
FeaturePlot(scTcells, reduction = "umap", features = "CD8B")
FeaturePlot(scTcells, reduction = "umap", features = "CD4")
```


```{r Identify Cluster 0}
VlnPlot(scTcells, features = "CCL5", cols = farbenblind15)
VlnPlot(scTcells, features = "CD160", cols = farbenblind15)
VlnPlot(scTcells, features = "ITGAE", cols = farbenblind15)
VlnPlot(scTcells, features = "TRBV27", cols = farbenblind15)
```


```{r Identify Cluster 0 and 1}
VlnPlot(scTcells, features = "IL1R1", cols = farbenblind15)
VlnPlot(scTcells, features = "IL1R2", cols = farbenblind15)
VlnPlot(scTcells, features = "FOXP3", cols = farbenblind15)
VlnPlot(scTcells, features = "BATF", cols = farbenblind15)
VlnPlot(scTcells, features = "CTLA4", cols = farbenblind15)
```


```{r Identify Cluster 2}
VlnPlot(scTcells, features = "KLF2", cols = farbenblind15)
VlnPlot(scTcells, features = "BACH2", cols = farbenblind15)
VlnPlot(scTcells, features = "IL7R", cols = farbenblind15)
VlnPlot(scTcells, features = "TCF7", cols = farbenblind15)
```


```{r Identify Cluster 3}
VlnPlot(scTcells, features = "TNFSF8", cols = farbenblind15)
VlnPlot(scTcells, features = "ICOS", cols = farbenblind15)
VlnPlot(scTcells, features = "CXCR4", cols = farbenblind15)
```


```{r Identify NK cells}
VlnPlot(scTcells, features = "GZMK", cols = farbenblind15)
VlnPlot(scTcells, features = "PRF1", cols = farbenblind15)
VlnPlot(scTcells, features = "CCL4", cols = farbenblind15)
VlnPlot(scTcells, features = "CD8B", cols = farbenblind15)
```


```{r Identify Cluster 5}
VlnPlot(scTcells, features = "FYN", cols = farbenblind15)
VlnPlot(scTcells, features = "SIK3", cols = farbenblind15)
VlnPlot(scTcells, features = "MALAT1", cols = farbenblind15)
```


```{r Identify Cluster 6}
VlnPlot(scTcells, features = "IL4I1", cols = farbenblind15)
VlnPlot(scTcells, features = "RORA", cols = farbenblind15)
VlnPlot(scTcells, features = "RORC", cols = farbenblind15)
VlnPlot(scTcells, features = "CCL20", cols = farbenblind15)
VlnPlot(scTcells, features = "IL17A", cols = farbenblind15)
```

```{r Identify Cluster 7}
VlnPlot(scTcells, features = "KLF6", cols = farbenblind15)
VlnPlot(scTcells, features = "FOS", cols = farbenblind15)
VlnPlot(scTcells, features = "JUNB", cols = farbenblind15)
VlnPlot(scTcells, features = "CD69", cols = farbenblind15)
```


```{r Identify Cluster 8}
VlnPlot(scTcells, features = "FOXP3", cols = farbenblind15)
VlnPlot(scTcells, features = "CD177", cols = farbenblind15)
VlnPlot(scTcells, features = "CCR8", cols = farbenblind15)
VlnPlot(scTcells, features = "IKZF2", cols = farbenblind15)
VlnPlot(scTcells, features = "TNFRSF4", cols = farbenblind15)
VlnPlot(scTcells, features = "TNFRSF18", cols = farbenblind15) #GITR
```


```{r Identify Cluster 9}
VlnPlot(scTcells, features = "TYROBP", cols = farbenblind15)
VlnPlot(scTcells, features = "FCER1G", cols = farbenblind15)
VlnPlot(scTcells, features = "KLRC1", cols = farbenblind15)
VlnPlot(scTcells, features = "NCAM1", cols = farbenblind15)
```


```{r Identify Cluster 10}
VlnPlot(scTcells, features = "MKI67", cols = farbenblind15)
VlnPlot(scTcells, features = "CDK1", cols = farbenblind15)
VlnPlot(scTcells, features = "TYMS", cols = farbenblind15)
```


```{r TRB Influence on Clustering}
TRB_transcripts <- rownames(scTcells[["RNA"]])[grep("TRBV", rownames(scTcells[["RNA"]]))]
TRD_transcripts <- rownames(scTcells[["RNA"]])[grep("TRDV", rownames(scTcells[["RNA"]]))]

FeaturePlot(scTcells, reduction = "umap", features = "TRBV2")
FeaturePlot(scTcells, reduction = "umap", features = "TRBV3-1")

FeaturePlot(scTcells, reduction = "umap", features = "TRDV1")
FeaturePlot(scTcells, reduction = "umap", features = "TRDV2")
```

```{r Cluster over time}

Cluster_over_time <- scTcells@meta.data %>% group_by(date, SCT_snn_res.0.6) %>% 
  summarise(n = n()) %>% mutate(Freq = n/sum(n))

ggplot(Cluster_over_time, aes(x = date, y = Freq, fill = SCT_snn_res.0.6)) + 
  geom_col(color = "black") + scale_fill_manual(values = farbenblind15)

```


```{r Marker Genes Clusters, fig.height=12, fig.width=10}
FeaturePlot(scTcells, reduction = "umap", features = "IL17A")

# Basic Heatmap mit Marker Genen 
top5_genes <- Tcell_markers_06 %>% group_by(cluster) %>% dplyr::filter(avg_log2FC > 1) %>%
  slice_head(n = 5) %>% ungroup()

DoHeatmap(scTcells, features = unique(top5_genes$gene), assay = "SCT", slot = "scale.data",
          group.colors = farbenblind15) + NoLegend()

DotPlot(scTcells, features = unique(top5_genes$gene), group.by = "SCT_snn_res.0.6", 
        assay = "SCT") + coord_flip()

saveRDS(scTcells, file = "Tcells_CCA_subclustering.rds")
```

