---
title: "T Cell Cytokines and Chemokines"
author: "Julia Hitschfel"
date: "2025-11-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Seurat)
library(SeuratObject)
library(scDblFinder)
library(SingleCellExperiment)
library(dplyr)
library(ggplot2)
library(colorspace)
library(RColorBrewer)
library(viridis)
library(pheatmap)
```

## T Cell effector molecule expression


```{r Import dataset and }
Tcell_scobject <- readRDS(file = "Tcells_CCA_subclustering.rds")

Idents(Tcell_scobject) <- "SCT_snn_res.0.6"

Effector_list <- c("IL1A", "IL1B","IL2", "IL5", "IL6", "IL7", "CXCL8", "IL10", "IL12A", "TXLNA",
                   "IL15", "IL16", "IL17A", "IL18", "IL19", "IL21", "IL22", "IL26", "EBI3", "IL32",
                   "IL33", "GZMB", "PRF1", "GNLY", "GZMA", "GZMK", "TGFB1", "IFNG", "CXCL10",
                   "CXCL13", "CCL4", "CCL5", "TNF", "LTA", "XCL1", "XCL2")

DoHeatmap(Tcell_scobject, features = unique(Effector_list), assay = "SCT", slot = "scale.data") +
  NoLegend()
```


```{r Scale RNA Data for Heatmap}
DefaultAssay(Tcell_scobject) <- "RNA"
Tcell_scobject <- NormalizeData(Tcell_scobject)
Tcell_scobject <- ScaleData(Tcell_scobject, features = rownames(Tcell_scobject))

DoHeatmap(Tcell_scobject, features = unique(Effector_list), assay = "RNA", slot = "scale.data") +
  NoLegend()
```


```{r Pseudobulk, fig.height=10}
pseudo_Tcells <- AggregateExpression(Tcell_scobject, assays = "RNA", return.seurat = T, 
                                     group.by = "ident")

DoHeatmap(pseudo_Tcells, features = unique(Effector_list), assay = "RNA", slot = "scale.data") +
  NoLegend()

Effector_gene_rows <- which(rownames(pseudo_Tcells@assays$RNA$scale.data) %in% Effector_list)
Effector_genes <- pseudo_Tcells@assays$RNA$scale.data[Effector_gene_rows,]

pheatmap(Effector_genes)

pheatmap(Effector_genes, color = viridis(100))
```


```{r Cluster over time}
Cluster_over_time <- Tcell_scobject@meta.data %>% group_by(date, SCT_snn_res.0.6) %>% 
  summarise(n = n()) %>% mutate(Freq = n/sum(n))

farbenblind15 <- c("#000000","#004949","#009292","#FF6DB6","#FFB6DB",
                  "#490092","#006DDB","#B66DFF","#6DB6FF","#B6DBFF",
                  "#920000","#924900","#DB6D00","#24FF24","#FFFF6D") 

ggplot(Cluster_over_time, aes(x = date, y = Freq, fill = SCT_snn_res.0.6)) + 
  geom_col(color = "black") + scale_fill_manual(values = farbenblind15)
```

Based on markergene expression and effector molecule expression, we propose the following preliminary annotation:  

```{r T cell Annotations}
Markers_T_Clusters <- FindAllMarkers(Tcell_scobject, logfc.threshold = 0.25, min.pct = 0.25, 
                                     only.pos = T)

write.csv(Markers_T_Clusters, file = "T_cell_subclustering_CCAintegration_marker_genes.csv")

Tcell_scobject <- RenameIdents(Tcell_scobject, 
                         '0' = 'CD8_TRM', 
                       '1' = 'Treg_1', 
                       '2' = 'TCM', 
                       '3' = 'TPH-like', 
                       '4' = 'CD8_GzmK', 
                       '5' = 'Quiescent_T', 
                       '6' = 'Th17-like', 
                       '7' = 'TNFa+_Tcells', 
                       '8' = 'Treg_2',
                       '9' = 'NK_or_NKT', 
                       '10' = 'Proliferating')

saveRDS(Tcell_scobject, file = "Tcells_CCAintegration_annotation.rds")
```

```{r Heatmap mit Labels, fig.height=10}
colnames(Effector_genes) <- c('CD8_TRM', 'Treg_1', 'TCM', 'TPH-like', 'CD8_GzmK', 'Quiescent_T', 
                              'Th17-like', 'TNFa+_Tcells', 'Treg_2','NK_or_NKT', 'Proliferating')

pheatmap(Effector_genes)

pheatmap(Effector_genes, color = viridis(100))
```

```{r Cluster over time annotated}
Tcell_scobject$Annotation <- Idents(Tcell_scobject)

Cluster_over_time_ann <- Tcell_scobject@meta.data %>% group_by(date, Annotation) %>% 
  summarise(n = n()) %>% mutate(Freq = n/sum(n))

ggplot(Cluster_over_time_ann, aes(x = date, y = Freq, fill = Annotation)) + 
  geom_col(color = "black") + scale_fill_manual(values = farbenblind15)
```
