---
title: "DESeq2_Fibroblasts"
author: "Julia Hitschfel"
date: "2026-02-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Seurat)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(clusterProfiler)
library(DESeq2)
library(msigdbr)
library(ggforce)
library(tidytext)
library(plotly)
```

```{r Fibroblast DEG}
all.cells.seurat <- readRDS("integrated_seurat_refined_annotations.rds")

all.cells.seurat$Fibroblasts <- ifelse(grepl("Fibroblast", all.cells.seurat$Annotations.0.4), "Fibroblasts", 
                                       "Other")

fibroblasts.pseudo <- AggregateExpression(all.cells.seurat, assays = "RNA", 
                                        group.by = c("date", "Fibroblasts"), slot = "counts",
                                        return.seurat = F)

# Manipulate the matrix to fit DESeq2 input
matrix.t <- t(fibroblasts.pseudo$RNA)
count.data.frame <- as.data.frame(matrix.t)
splitRows <- gsub('.*_', '', rownames(count.data.frame))
cell.type.list <- split.data.frame(count.data.frame, f = factor(splitRows))

#Retranspose the matrix and fix column names for all elements of the list
cell.type.list.t <- lapply(cell.type.list, function(x){
	rownames(x) <- gsub('(.*)_.*', '\\1', rownames(x))
	t(x)
})

# Create meta.data for count matrix
col.data <- data.frame(samples = colnames(cell.type.list.t$`Fibroblasts`))

col.data$treatment <- ifelse(col.data$samples == "g2024-07-15" | col.data$samples == "g2024-11-28" |
                               col.data$samples == "g2025-02-17", "pre_CART", "post_CART")

# Perform DESeq2 for all Fibroblasts
count.data.Fibroblasts <- cell.type.list.t$`Fibroblasts`

# To prevent the B cell pathways and IG genes from popping up, I am removing all the IG transcripts at this step:

IG.transcripts <- c(which(grepl("^IGH", rownames(count.data.Fibroblasts)) == T), 
                    which(grepl("^IGL", rownames(count.data.Fibroblasts)) == T), 
                    which(grepl("^IGK", rownames(count.data.Fibroblasts)) == T))

count.data.Fibroblasts.noIG <- count.data.Fibroblasts[-IG.transcripts,]
class(count.data.Fibroblasts.noIG) <- "integer"


dds <- DESeqDataSetFromMatrix(countData = count.data.Fibroblasts.noIG, 
				colData =  col.data,
 				design = ~ treatment)

#Remove all genes with fewer than 10 reads 
keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep,]

dds <- DESeq(dds)

resultsNames(dds)

#Generate results object
res <- results(dds, name = "treatment_pre_CART_vs_post_CART")
res 

res_df <- as.data.frame(res)

# Sort dataframe for adjusted p value and show top20 results 
res_df_sort <- res_df[order(res_df$padj),]
head(res_df_sort, 20)

res_df_sort$sign.log.10.p <-
  sign(res_df_sort$log2FoldChange)*(-log10(res_df_sort$pvalue))
res_df_sort <- res_df_sort %>% filter(!is.na(sign.log.10.p))
res_df_sort <- res_df_sort[order(res_df_sort$sign.log.10.p, decreasing = T),]

ranked_genes <- as.vector(res_df_sort$sign.log.10.p)
names(ranked_genes) <- rownames(res_df_sort)

## Volcano Plot
Fibro.volcano.data <- res_df
Fibro.volcano.data$log10.padj <- -log10(Fibro.volcano.data$padj)
Fibro.volcano.data$diffexpressed <- ifelse(Fibro.volcano.data$log10.padj > -log10(0.05) & 
                                        abs(Fibro.volcano.data$log2FoldChange) > 1, "Up or Down", "NS")
Fibro.volcano.data$gene <- rownames(Fibro.volcano.data)

# Volcano plot
Fibro_volcano_plot <- ggplot(Fibro.volcano.data, aes(x = log2FoldChange, y = log10.padj, 
                       color = diffexpressed, text = gene)) +
                        geom_point(size = 1.5) +
                      scale_color_manual(values = c("lightgrey", "darkblue")) + 
                      labs(title = "Volcano Plot", x = "Log2(Fold Change)", y = "-log10(adj. P-value)") + 
                      theme_minimal()
  
ggplotly(Fibro_volcano_plot, tooltip = "text")
```


```{r Labeled volcano plot}
Inflammation.gene.list <- c("IL6", "CXCL1", "CXCL2", "CXCL3", "CXCL5", "CXCL8", "CXCL13", "IL13RA2", "CCL19", "CCL21")
ECM.remodeling.gene.list <- c("MMP1", "MMP3", "MMP13", "ADAM12", "ADAMTS12", "FAP", "CTHRC1", "FBLN2")
ECM.stabilization.gene.list <- c("PPARG", "SPARCL1", "COL15A1", "CLEC3B", "SLIT2", "SLIT3")

Fibro.volcano.data$Category <- ifelse(Fibro.volcano.data$gene %in% Inflammation.gene.list, "Inflammation/Leukocyte Recruitment", "Other")
Fibro.volcano.data$Category <- ifelse(Fibro.volcano.data$gene %in% ECM.remodeling.gene.list, "ECM Remodeling", Fibro.volcano.data$Category)
Fibro.volcano.data$Category <- ifelse(Fibro.volcano.data$gene %in% ECM.stabilization.gene.list, "ECM Stabilization and Restoration",
                                      Fibro.volcano.data$Category)

Fibro.volcano.data$Category <- factor(Fibro.volcano.data$Category, levels = c("ECM Remodeling", "ECM Stabilization and Restoration", 
                                                                        "Inflammation/Leukocyte Recruitment", "Other"))

points_to_label <- subset(Fibro.volcano.data, Category != "Other")

# Volcano plot
Fibro_volcano_plot <- ggplot(Fibro.volcano.data, aes(x = log2FoldChange, y = log10.padj)) +
  geom_point(data = subset(Fibro.volcano.data, Category == "Other"), color = "snow2", size = 1) +
  geom_point(data = subset(Fibro.volcano.data, Category == "ECM Remodeling"), aes(color = 'ECM Remodeling'), size = 1.25) +
  geom_point(data = subset(Fibro.volcano.data, Category == "ECM Stabilization and Restoration"), 
             aes(color = 'ECM Stabilization and Restoration'), size = 1.25) +
  geom_point(data = subset(Fibro.volcano.data, Category == "Inflammation/Leukocyte Recruitment"), 
             aes(color = 'Inflammation/Leukocyte Recruitment'), size = 1.25) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "cornsilk2") +
  geom_vline(xintercept = 1, linetype = "dashed", color = "cornsilk2")  +
  geom_vline(xintercept = -1, linetype = "dashed", color = "cornsilk2") +
  geom_text_repel(data = points_to_label, aes(label = gene), color = "black", size = 3) +
    scale_color_manual(name = 'Category', 
                       breaks = c('ECM Remodeling', 'ECM Stabilization and Restoration', 'Inflammation/Leukocyte Recruitment'), 
                       values = c('ECM Remodeling' = "chartreuse4", 'ECM Stabilization and Restoration' = "dodgerblue1", 
                                  'Inflammation/Leukocyte Recruitment' ="firebrick1")) +
  xlim(-15,15) +
  coord_fixed(ratio = 1.875) +
  labs(x = expression("Log"[2] ~ "(Fold Change)"), y = expression("-log"[10] ~ "(adj. P-value)")) + 
  theme_classic()

Fibro_volcano_plot

ggsave("/Figures/Volcano_Fibroblasten_Labels.tiff", plot = Fibro_volcano_plot,
       device = "tiff", dpi = 300, width = 8, height = 6, units = "in", compression = "lzw")

```

```{r GSEA for all fibroblasts combined}
# Import the MSigDB Hallmark Collection
hallmark<- msigdbr(collection = "H") %>% 
  dplyr::select(gs_name, gene_symbol)

head(hallmark)

h2 <- msigdbr(collection = "H") %>% 
  dplyr::select(gs_name, gs_description)

#set seed
set.seed(123)
#run GSEA
Fibro.HALLMARK <- GSEA(ranked_genes, TERM2GENE = hallmark, TERM2NAME = h2, seed=TRUE)

head(Fibro.HALLMARK)

print(paste0(Fibro.HALLMARK@result$ID, " - NES:  ", Fibro.HALLMARK@result$NES,  " - padj:  ",
             Fibro.HALLMARK@result$p.adjust))

Fibro.Hallmark.df <- data.frame(ID = Fibro.HALLMARK@result$ID, 
                             NES = Fibro.HALLMARK@result$NES, 
                             padj = Fibro.HALLMARK@result$p.adjust)

Fibro.Hallmark.df <- Fibro.Hallmark.df[order(Fibro.Hallmark.df$NES),]
Fibro.Hallmark.df$ID <- factor(Fibro.Hallmark.df$ID, levels = Fibro.Hallmark.df$ID)

ggplot(Fibro.Hallmark.df, aes(x = ID, y = NES, fill = padj)) + geom_col() + 
  scale_fill_gradient() + coord_flip() + theme_minimal()


# GO und REACTOME
GO_BP <- msigdbr(collection = "C5", subcollection = "GO:BP") %>% 
  dplyr::select(gs_name, gene_symbol)

GO_BP_t2n <- msigdbr(collection = "C5", subcollection = "GO:BP") %>% 
  dplyr::select(gs_name, gs_description)

#run GSEA
Fibro.GO.BP <- GSEA(ranked_genes, TERM2GENE = GO_BP, TERM2NAME = GO_BP_t2n, seed=TRUE)

Fibro.GO.BP.df <- data.frame(ID = Fibro.GO.BP@result$ID, 
                             NES = Fibro.GO.BP@result$NES, 
                             padj = Fibro.GO.BP@result$p.adjust)

Fibro.GO.BP.df.top10.up <- Fibro.GO.BP.df %>% filter(NES > 0) %>% slice_min(padj, n = 10)
Fibro.GO.BP.df.top10.dn <- Fibro.GO.BP.df %>% filter(NES < 0) %>% slice_min(padj, n = 10)
Fibro.GO.BP.df.top20 <- rbind(Fibro.GO.BP.df.top10.up, Fibro.GO.BP.df.top10.dn)

Fibro.GO.BP.df.top20 <- Fibro.GO.BP.df.top20[order(Fibro.GO.BP.df.top20$NES),]
Fibro.GO.BP.df.top20$ID <- factor(Fibro.GO.BP.df.top20$ID, levels = Fibro.GO.BP.df.top20$ID)

ggplot(Fibro.GO.BP.df.top20, aes(x = ID, y = NES, fill = padj)) + geom_col() + 
  scale_fill_gradient() + coord_flip() + labs(title = "GO:BP Top 20 enriched Gene Sets in Fibroblasts") +
  theme_minimal() + 
  theme(axis.text.x = element_text(size = 7), axis.text.y = element_text(size = 7))
  


## GSEA mit REACTOME
REACTOME <- msigdbr(collection = "C2", subcollection = "CP:REACTOME") %>% 
  dplyr::select(gs_name, gene_symbol)

REACTOME_t2n <- msigdbr(collection = "C2", subcollection = "CP:REACTOME") %>% 
  dplyr::select(gs_name, gs_description)

#run GSEA
Fibro.REACTOME <- GSEA(ranked_genes, TERM2GENE = REACTOME, TERM2NAME = REACTOME_t2n, seed=TRUE)

Fibro.REACTOME.df <- data.frame(ID = Fibro.REACTOME@result$ID, 
                             NES = Fibro.REACTOME@result$NES, 
                             padj = Fibro.REACTOME@result$p.adjust)

Fibro.REACTOME.df.top10.up <- Fibro.REACTOME.df %>% filter(NES > 0) %>% slice_min(padj, n = 10) %>%
  slice_max(NES, n = 10)
Fibro.REACTOME.df.top10.dn <- Fibro.REACTOME.df %>% filter(NES < 0) %>% slice_min(padj, n = 10)
Fibro.REACTOME.df.top20 <- rbind(Fibro.REACTOME.df.top10.up, Fibro.REACTOME.df.top10.dn)

Fibro.REACTOME.df.top20 <- Fibro.REACTOME.df.top20[order(Fibro.REACTOME.df.top20$NES),]
Fibro.REACTOME.df.top20$ID <- factor(Fibro.REACTOME.df.top20$ID, levels = Fibro.REACTOME.df.top20$ID)

ggplot(Fibro.REACTOME.df.top20, aes(x = ID, y = NES, fill = padj)) + geom_col() +
  scale_fill_gradient() + coord_flip() + theme_minimal() + 
  labs(title = "REACTOME Top 20 enriched Gene Sets in Fibroblasts") + 
  theme(axis.text.x = element_text(size = 7), axis.text.y = element_text(size = 7))
```

```{r GSEA summary plot, fig.width=9, fig.height=7}
all.GSEA.fibro.noREACT <- rbind(Fibro.Hallmark.df, Fibro.GO.BP.df.top20)
all.GSEA.fibro.noREACT$DB <- ifelse(grepl("HALLMARK", all.GSEA.fibro.noREACT$ID), "HALLMARK", NA)
all.GSEA.fibro.noREACT$DB <- ifelse(grepl("GOBP", all.GSEA.fibro.noREACT$ID), "GOBP", all.GSEA.fibro.noREACT$DB)
all.GSEA.fibro.noREACT$DB <- factor(all.GSEA.fibro.noREACT$DB, levels = c("HALLMARK", "GOBP"))

all.GSEA.fibro.noREACT$Status <- ifelse(all.GSEA.fibro.noREACT$NES < 0, "post CART", NA)
all.GSEA.fibro.noREACT$Status <- ifelse(all.GSEA.fibro.noREACT$NES > 0, "pre CART", all.GSEA.fibro.noREACT$Status)

all.GSEA.fibro.noREACT.preCAR <- all.GSEA.fibro.noREACT %>% filter(Status == "pre CART") %>% group_by(DB) %>% 
  slice_max(NES, n = 5)
all.GSEA.fibro.noREACT.postCAR <- all.GSEA.fibro.noREACT %>% filter(Status == "post CART") %>% group_by(DB) %>% 
  slice_min(NES, n = 5)
all.GSEA.fibro.noREACT.top5 <- rbind(all.GSEA.fibro.noREACT.preCAR, all.GSEA.fibro.noREACT.postCAR)
all.GSEA.fibro.noREACT.top5$Status <- factor(all.GSEA.fibro.noREACT.top5$Status, levels = c("pre CART", "post CART"))

all.GSEA.fibro.noREACT.top5$ID <- gsub("GOBP", "", all.GSEA.fibro.noREACT.top5$ID)
all.GSEA.fibro.noREACT.top5$ID <- gsub("HALLMARK", "", all.GSEA.fibro.noREACT.top5$ID)
all.GSEA.fibro.noREACT.top5$ID <- gsub("_", " ", all.GSEA.fibro.noREACT.top5$ID)

all.GSEA.fibro.noREACT.top5 <- all.GSEA.fibro.noREACT.top5 %>% mutate(log.10.padj = -log10(padj))

GSEA.Fibro.plot <- ggplot(all.GSEA.fibro.noREACT.top5, aes(x = Status, y = reorder_within(ID, NES, DB))) + 
  geom_point(aes(color = log.10.padj, size = abs(NES))) + scale_y_reordered() + scale_size(range = c(3,6)) +
  scale_x_discrete(expand = c(0.5,0.5)) +
  ggforce::facet_col(~DB, scales = "free_y", space = "free") +
   scale_color_gradient(low = "darkblue", high = "purple") + 
  labs(color = "-log10\n(adj. P-value)", size = "NES") +
  theme_classic(base_size = 13) +
  theme(
    axis.title = element_blank(),
    axis.text.y = element_text(size = 10),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold"),
    legend.position = "right", 
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

GSEA.Fibro.plot

ggsave("/Figures/GSEA_summary_Fibroblasts_noREACTOME.tiff", 
       plot = GSEA.Fibro.plot, device = "tiff", dpi = 300, width = 9, height = 7, units = "in", compression = "lzw")


### Selected Gene Sets
all.GSEA.fibro.selectGS.preCAR <- all.GSEA.fibro.noREACT %>% filter(Status == "pre CART") %>% group_by(DB) %>% 
  slice_max(NES, n = 10)
all.GSEA.fibro.selectGS.postCAR <- all.GSEA.fibro.noREACT %>% filter(Status == "post CART") %>% group_by(DB) %>% 
  slice_min(NES, n = 10)
all.GSEA.fibro.selectGS.top10 <- rbind(all.GSEA.fibro.selectGS.preCAR, all.GSEA.fibro.selectGS.postCAR)
GS.to.filter <- c("GOBP_CELL_SURFACE_RECEPTOR_PROTEIN_SERINE_THREONINE_KINASE_SIGNALING_PATHWAY", 
                  "GOBP_EXTERNAL_ENCAPSULATING_STRUCTURE_ORGANIZATION", "GOBP_SKELETAL_SYSTEM_DEVELOPMENT", 
                  "GOBP_RESPONSE_TO_OXYGEN_LEVELS", "GOBP_GENERATION_OF_PRECURSOR_METABOLITES_AND_ENERGY", 
                  "GOBP_EXCITATORY_SYNAPSE_ASSEMBLY", "GOBP_P_BODY_ASSEMBLY", "GOBP_DENDRITE_DEVELOPMENT",
                  "GOBP_REGULATION_OF_DENDRITE_DEVELOPMENT", "GOBP_POSITIVE_THYMIC_T_CELL_SELECTION",
                  "GOBP_NEUTROPHIL_ACTIVATION_INVOLVED_IN_IMMUNE_RESPONSE")

all.GSEA.fibro.selectGS.top10 <- all.GSEA.fibro.selectGS.top10 %>% filter(!ID %in% GS.to.filter)
all.GSEA.fibro.selectGS.top10$Status <- factor(all.GSEA.fibro.selectGS.top10$Status, levels = c("pre CART", "post CART"))

all.GSEA.fibro.selectGS.top10$ID <- gsub("GOBP", "", all.GSEA.fibro.selectGS.top10$ID)
all.GSEA.fibro.selectGS.top10$ID <- gsub("HALLMARK", "", all.GSEA.fibro.selectGS.top10$ID)
all.GSEA.fibro.selectGS.top10$ID <- gsub("_", " ", all.GSEA.fibro.selectGS.top10$ID)

all.GSEA.fibro.selectGS.top10 <- all.GSEA.fibro.selectGS.top10 %>% mutate(log.10.padj = -log10(padj))

GSEA.Fibro.plot.select <- ggplot(all.GSEA.fibro.selectGS.top10, aes(x = Status, y = reorder_within(ID, NES, DB))) + 
  geom_point(aes(color = log.10.padj, size = abs(NES))) + scale_y_reordered() + scale_size(range = c(3,6)) +
  scale_x_discrete(expand = c(0.5,0.5)) +
  ggforce::facet_col(~DB, scales = "free_y", space = "free") +
   scale_color_gradient(low = "darkblue", high = "purple") + 
  labs(color = "-log10\n(adj. P-value)", size = "NES") +
  theme_classic(base_size = 13) +
  theme(
    axis.title = element_blank(),
    axis.text.y = element_text(size = 10),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold"),
    legend.position = "right", 
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

GSEA.Fibro.plot.select

ggsave(
  "/Figures/GSEA_summary_Fibroblasts_selected_gene_sets.tiff",
  plot = GSEA.Fibro.plot.select, device = "tiff", dpi = 300, width = 8, height = 7, units = "in", compression = "lzw")
```
