---
title: "PCA_and_marker_all_cells"
author: "Julia Hitschfel"
date: "2026-03-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Seurat)
library(dplyr)
library(DESeq2)
library(ggplot2)
library(ggrepel)
library(clusterProfiler)
library(tidyverse)
library(msigdbr)
library(ggpubr)
library(rstatix)
library(RColorBrewer)
library(viridis)
library(pheatmap)

farbenblind15 <- c("#000000","#004949","#009292","#FF6DB6","#FFB6DB",
                  "#490092","#006DDB","#B66DFF","#6DB6FF","#B6DBFF",
                  "#920000","#924900","#DB6D00","#24FF24","#FFFF6D")
```


```{r Marker genes all cells visualizations}
all.cells.seurat <- readRDS("integrated_seurat_refined_annotations.rds")


Idents(all.cells.seurat) <- factor(Idents(all.cells.seurat), 
                            levels = c("B cells","Distal Enterocytes", "Endothelial Cells",
                                       "Fibroblasts_1", "Fibroblasts_2",
                                       "Intestinal Epithelial Cells_1",
                                       "Intestinal Epithelial Cells_2", 
                                       "Mast Cells", "Myeloid Cells_1",
                                       "Myeloid Cells_2", "Neurons", "Secretory Epithelial Cells", 
                                       "Smooth Muscle Cells_1", "Smooth Muscle Cells_2", 
                                       "T cells_1", "T cells_2", "Other"))

Markers.all.cells <- FindAllMarkers(all.cells.seurat, logfc.threshold = 0.25, min.pct = 0.1, only.pos = T)

top5_genes <- Markers.all.cells %>% group_by(cluster) %>% dplyr::filter(avg_log2FC > 1) %>%
  slice_head(n = 5) %>% ungroup()

DotPlot(all.cells.seurat, features = unique(top5_genes$gene), 
        assay = "SCT") + coord_flip() + theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("/Figures/Marker_genes_all_cells.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, height = 14, width = 10, units = "in", compression = "lzw")

## Heatmap
pseudo_allcells <- AggregateExpression(all.cells.seurat, assays = "RNA", return.seurat = T, 
                                     group.by = "ident")

pseudo_allcells <- ScaleData(pseudo_allcells, features = unique(top5_genes$gene))
Idents(pseudo_allcells) <- factor(Idents(pseudo_allcells), levels = rev(levels(Idents(pseudo_allcells))))
Marker_gene_rows <- which(rownames(pseudo_allcells@assays$RNA$scale.data) %in% unique(top5_genes$gene))
Marker_genes <- pseudo_allcells@assays$RNA$scale.data[Marker_gene_rows,]

png("/Figures/Marker_genes_all_cells_heatmap.tiff", width = 900, 
    height = 1600, res = 150)
pheatmap(Marker_genes, main = "Gene expression \n(scaled z-score per gene)", cluster_cols = F, angle_col = 45)
dev.off()

png("/Figures/Marker_genes_all_cells_heatmap_viridis.tiff",
    width = 900, height = 1600, res = 150)
pheatmap(Marker_genes, main = "Gene expression \n(scaled z-score per gene)", cluster_cols = F, angle_col = 45, color = viridis(100))
dev.off()

# Better with average expression
Marker_gene_rows <- which(rownames(pseudo_allcells@assays$RNA$data) %in% unique(top5_genes$gene))
Marker_genes <- pseudo_allcells@assays$RNA$data[Marker_gene_rows,]

png("/Figures/Marker_genes_all_cells_heatmap_viridis_norm_exp.tiff",
    width = 900, height = 1600, res = 150)
pheatmap(Marker_genes, main = "Normalized gene expression", cluster_cols = F, angle_col = 45, color = viridis(100))
dev.off()
```


```{r markers not flipped, fig.width=15, fig.height=6}
Idents(all.cells.seurat) <- factor(Idents(all.cells.seurat), levels = rev(levels(Idents(all.cells.seurat))))
DotPlot(all.cells.seurat, features = unique(top5_genes$gene), assay = "SCT") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

ggsave("/Figures/Marker_genes_all_cells_flip.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, width = 15, height = 6, units = "in", compression = "lzw")
```



```{r T cells CXCL13}
Tcell.seurat <- readRDS("Tcells_CCAintegration_annotation_TCRs.rds")

VlnPlot(Tcell.seurat, features = "CXCL13", idents = "TPH-like", group.by = "date") + 
  scale_fill_manual(labels = c("Pre-B", "Post-B", "Pre-CART", "D10", "Mo1", "Mo5", "Mo8"), values = farbenblind15) + 
  scale_x_discrete(labels = c("Pre-B", "Post-B", "Pre-CART", "D10", "Mo1", "Mo5", "Mo8"))

ggsave("/Figures/Tcells_TPH_CXCL13_timepoints.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, width = 8, height = 6, units = "in", compression = "lzw")

VlnPlot(Tcell.seurat, features = "IL21", idents = "TPH-like", group.by = "date") + 
  scale_fill_manual(labels = c("Pre-B", "Post-B", "Pre-CART", "D10", "Mo1", "Mo5", "Mo8"), values = farbenblind15) + 
  scale_x_discrete(labels = c("Pre-B", "Post-B", "Pre-CART", "D10", "Mo1", "Mo5", "Mo8"))

ggsave("/Figures/Tcells_TPH_IL21_timepoints.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, width = 8, height = 6, units = "in", compression = "lzw")

VlnPlot(Tcell.seurat, features = "CD40LG", idents = "TPH-like", group.by = "date")
VlnPlot(Tcell.seurat, features = "SELL", idents = "TPH-like", group.by = "date")
VlnPlot(Tcell.seurat, features = "CCL5", idents = "TPH-like", group.by = "date")

VlnPlot(Tcell.seurat, features = "IL21", idents = "Th17-like", group.by = "date")
VlnPlot(Tcell.seurat, features = "GPR15", idents = "Th17-like", group.by = "date")
VlnPlot(Tcell.seurat, features = "CCL5", idents = "Th17-like", group.by = "date")

VlnPlot(Tcell.seurat, features = "IL17A", idents = "Th17-like", group.by = "date") + 
  scale_fill_manual(labels = c("Pre-B", "Post-B", "Pre-CART", "D10", "Mo1", "Mo5", "Mo8"), values = farbenblind15) + 
  scale_x_discrete(labels = c("Pre-B", "Post-B", "Pre-CART", "D10", "Mo1", "Mo5", "Mo8"))

ggsave("/Figures/Tcells_Th17_IL17A_timepoints.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, width = 8, height = 6, units = "in", compression = "lzw")

VlnPlot(Tcell.seurat, features = "GPR15", idents = "Treg_1", group.by = "date")
VlnPlot(Tcell.seurat, features = "IRF1", idents = "Treg_1", group.by = "date")

VlnPlot(Tcell.seurat, features = "IL10", idents = "Treg_1", group.by = "date") + 
  scale_fill_manual(labels = c("Pre-B", "Post-B", "Pre-CART", "D10", "Mo1", "Mo5", "Mo8"), values = farbenblind15) + 
  scale_x_discrete(labels = c("Pre-B", "Post-B", "Pre-CART", "D10", "Mo1", "Mo5", "Mo8"))

ggsave("/Figures/Tcells_Treg1_IL10_timepoints.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, width = 8, height = 6, units = "in", compression = "lzw")

## Treg2 does not produce IL10

VlnPlot(Tcell.seurat, features = "IL17A", idents = "Treg_1", group.by = "date") + 
  scale_fill_manual(labels = c("Pre-B", "Post-B", "Pre-CART", "D10", "Mo1", "Mo5", "Mo8"), values = farbenblind15) + 
  scale_x_discrete(labels = c("Pre-B", "Post-B", "Pre-CART", "D10", "Mo1", "Mo5", "Mo8"))

ggsave("/Figures/Tcells_Treg1_IL17A_timepoints.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, width = 8, height = 6, units = "in", compression = "lzw")

## Treg2 also does not produce IL17A

```

```{r Makrophagen}
myeloid.seurat <- readRDS("Myeloid_Cells_annotated.rds")

Macrophages.idents <- c("M1 Macrophages", "Inflammatory monocyte-derived Macrophages", "M2 Macrophages_1", 
                        "M2 Macrophages_2")

VlnPlot(myeloid.seurat, features = "CXCL9", idents = Macrophages.idents, group.by = "date") + 
  scale_fill_manual(labels = c("Pre-B", "Post-B", "Pre-CART", "D10", "Mo1", "Mo5", "Mo8"), values = farbenblind15) + 
  scale_x_discrete(labels = c("Pre-B", "Post-B", "Pre-CART", "D10", "Mo1", "Mo5", "Mo8"))

ggsave("/Figures/Macrophages_CXCL9_timepoints.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, width = 8, height = 6, units = "in", compression = "lzw")
```

```{r B cells, drop = FALSE}
Bcell.seurat <- readRDS("Bcell_v5_integrated_singleR_annotations.rds")

Bcell.seurat <- RenameIdents(Bcell.seurat, 'Plasmacells_1' = 'PC_1', 'Plasmacells_2' = 'PC_2', 'Plasmacells_3' = 'PC_3/PB', 
                              'Plasmacells_4' = 'PC_4', 'Plasmacells_5' = 'PC_5', 'Plasmablasts' = 'GC B cells')

VlnPlot(Bcell.seurat, features = "CXCR3", group.by = "date") + 
  scale_fill_manual(labels = c("Pre-B", "Post-B", "Pre-CART", "D10", "Mo1", "Mo5", "Mo8"), values = farbenblind15) + 
  scale_x_discrete(labels = c("Pre-B", "Post-B", "Pre-CART", "D10", "Mo1", "Mo5", "Mo8"))

ggsave("/Figures/Bcells_CXCR3_timepoints.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, width = 8, height = 6, units = "in", compression = "lzw")

VlnPlot(Bcell.seurat, features = "CXCR3") + 
  scale_fill_manual(values = farbenblind15)

ggsave("/Figures/Bcells_CXCR3_clusters.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, width = 8, height = 6, units = "in", compression = "lzw")


## ITGB7
VlnPlot(Bcell.seurat, features = "ITGB7", group.by = "date") + 
  scale_fill_manual(labels = c("Pre-B", "Post-B", "Pre-CART", "D10", "Mo1", "Mo5", "Mo8"), values = farbenblind15) + 
  scale_x_discrete(labels = c("Pre-B", "Post-B", "Pre-CART", "D10", "Mo1", "Mo5", "Mo8"))

ggsave("/Figures/Bcells_ITGB7_timepoints.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, width = 8, height = 6, units = "in", compression = "lzw")

VlnPlot(Bcell.seurat, features = "ITGB7") +
  scale_fill_manual(values = farbenblind15)

ggsave("/Figures/Bcells_ITGB7_clusters.tiff",
       plot = last_plot(), device = "tiff", dpi = 300, width = 8, height = 6, units = "in", compression = "lzw")
```

```{r Marker Genes Plots, fig.width=12, fig.height=10}
Tcell.seurat <- RenameIdents(Tcell.seurat, 'CD8_TRM' = 'CD8 Trm', 'Treg_1' = 'CCR6+ Treg', 'TCM' = 'Naive/CM', 'TPH-like' = 'Tph-like', 
                             'CD8_GzmK' = 'GzmK CD8', 'Quiescent_T' = 'Memory CD8', 'Th17-like' = 'Th17-like CD4', 
                             'TNFa+_Tcells' = 'Activated CD8', 'Treg_2' = 'Effector Treg', 'NK_or_NKT' = 'NK-like cytotoxic cells', 
                             'Proliferating' = 'Proliferating cells')

Idents(Tcell.seurat) <- factor(Idents(Tcell.seurat), 
                            levels = c("CD8 Trm", "GzmK CD8", "Naive/CM", "Tph-like", "Th17-like CD4", "CCR6+ Treg", "Effector Treg",
                                       "Activated CD8", "NK-like cytotoxic cells", "Memory CD8", "Proliferating cells"))

Markers.Tcells <- FindAllMarkers(Tcell.seurat, logfc.threshold = 0.25, min.pct = 0.1, only.pos = T)

top5_genes_Tcells <- Markers.Tcells %>% group_by(cluster) %>% dplyr::filter(avg_log2FC > 1) %>%
  slice_head(n = 5) %>% ungroup()

DotPlot(Tcell.seurat, features = unique(top5_genes_Tcells$gene), assay = "SCT") + coord_flip() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("/Figures/Marker_genes_Tcells.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, height = 12, width = 8, units = "in", compression = "lzw")

## Alternative Markers 
Tcell_markers <- c("CD8A", "CD8B", "ITGAE", "GZMB", "GZMA", "GZMM", "ITGB7", "CD69", "NKG7", "FOXP3", "CTLA4", "BATF", 
                   "TNFRSF18", "CCR6", "CCR4", "IL23R", "CXCR6", "IL17A", "IL26", "CCL20", "IL7R", "CCR7", "CXCR4", "TCF7", 
                   "KLF2", "CD4", "ICOS", "TOX2", "CXCL13", "IL21", "CCR7", "GZMK", "GZMH", "CCL5", 
                   "PRF1", "IL10", "FYN", "STAT4", "SELL", "TNF", "CD40LG", "CXCR6", "RORA", "RORC",  
                   "CCL20", "FOS", "FOSB", "JUN", "IFNG", "KLF6", "IKZF2", "CCR8", "IL2RA", "RTKN2", 
                   "TIGIT", "GNLY", "IL18", "NCAM1", "MKI67", "CCNB2", "PLK1", "TOP2A")

DotPlot(Tcell.seurat, features = unique(Tcell_markers), assay = "SCT") + coord_flip() + theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("/Figures/Marker_genes_Tcells_custom.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, height = 14, width = 8, units = "in", compression = "lzw")

## Heatmap
pseudo_Tcells <- AggregateExpression(Tcell.seurat, assays = "RNA", return.seurat = T,
                                     group.by = "ident")

pseudo_Tcells <- ScaleData(pseudo_Tcells, features = unique(top5_genes_Tcells$gene))
Idents(pseudo_Tcells) <- factor(Idents(pseudo_Tcells), levels = rev(levels(Idents(pseudo_Tcells))))
Marker_gene_rows <- which(rownames(pseudo_Tcells@assays$RNA$scale.data) %in% unique(top5_genes_Tcells$gene))
Marker_genes <- pseudo_Tcells@assays$RNA$scale.data[Marker_gene_rows,]

png("/Figures/Marker_genes_Tcells_heatmap.tiff", width = 900,
    height = 1800, res = 150)
pheatmap(Marker_genes, main = "Gene expression \n(scaled z-score per gene)", cluster_cols = F, angle_col = 45)
dev.off()

png("/Figures/Marker_genes_Tcells_heatmap_viridis.tiff",
    width = 900, height = 1800, res = 150)
pheatmap(Marker_genes, main = "Gene expression \n(scaled z-score per gene)", cluster_cols = F, angle_col = 45, color = viridis(100))
dev.off()

# flipped
Marker_genes_flip <- t(Marker_genes)

png("/Figures/Marker_genes_Tcells_heatmap_flipped.tiff", width = 2200,
    height = 700, res = 150)
pheatmap(Marker_genes_flip, main = "Gene expression \n(scaled z-score per gene)", cluster_rows = F, angle_col = 45, 
        cellheight = 16, cellwidth = 16,  treeheight_col = 0)
dev.off()

png("/Figures/Marker_genes_Tcells_heatmap_viridis_flipped.tiff",
    width = 2200, height = 700, res = 150)
pheatmap(Marker_genes_flip, main = "Gene expression \n(scaled z-score per gene)", cluster_rows = F, angle_col = 45, color = viridis(100), 
         cellheight = 16, cellwidth = 16, treeheight_col = 0)
dev.off()

## Custom marker genes Heatmap
pseudo_Tcells <- ScaleData(pseudo_Tcells, features = Tcell_markers)
Marker_gene_rows <- which(rownames(pseudo_Tcells@assays$RNA$scale.data) %in% unique(Tcell_markers))
Marker_genes <- pseudo_Tcells@assays$RNA$scale.data[Marker_gene_rows,]

png("/Figures/Marker_genes_Tcells_custom_heatmap.tiff", width = 900,
    height = 1800, res = 150)
pheatmap(Marker_genes, main = "Gene expression \n(scaled z-score per gene)", cluster_cols = F, angle_col = 45)
dev.off()

png("/Figures/Marker_genes_Tcells_custom_heatmap_viridis.tiff",
    width = 900, height = 1800, res = 150)
pheatmap(Marker_genes, main = "Gene expression \n(scaled z-score per gene)", cluster_cols = F, angle_col = 45, color = viridis(100))
dev.off()

# flipped custom marker genes
Marker_genes_custom_flip <- t(Marker_genes)

png("/Figures/Marker_genes_Tcells_custom_heatmap_flipped.tiff", width = 2200,
    height = 700, res = 150)
pheatmap(Marker_genes_custom_flip, main = "Gene expression \n(scaled z-score per gene)", cluster_rows = F, angle_col = 45,
        cellheight = 20, cellwidth = 12,  treeheight_col = 0)
dev.off()

png("/Figures/Marker_genes_Tcells_custom_heatmap_viridis_flipped.tiff",
    width = 2200, height = 700, res = 150)
pheatmap(Marker_genes_custom_flip, main = "Gene expression \n(scaled z-score per gene)", cluster_rows = F, angle_col = 45, color = viridis(100), 
         cellheight = 20, cellwidth = 12, treeheight_col = 0)
dev.off()


#Flipped Dotplot
Idents(Tcell.seurat) <- factor(Idents(Tcell.seurat), levels = rev(levels(Idents(Tcell.seurat))))

DotPlot(Tcell.seurat, features = unique(top5_genes_Tcells$gene), assay = "SCT") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

ggsave("/Figures/Marker_genes_Tcells_flip.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, width = 12, height = 4, units = "in", compression = "lzw")



### B cells 
Markers.Bcells <- FindAllMarkers(Bcell.seurat, logfc.threshold = 0.25, min.pct = 0.1, only.pos = T)

top5_genes_Bcells <- Markers.Bcells %>% group_by(cluster) %>% dplyr::filter(avg_log2FC > 1) %>%
  slice_head(n = 5) %>% ungroup()

DotPlot(Bcell.seurat, features = unique(top5_genes_Bcells$gene), 
        assay = "RNA") + coord_flip() + theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("/Figures/Marker_genes_Bcells.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, height = 9, width = 6, units = "in", compression = "lzw")

Idents(Bcell.seurat) <- factor(Idents(Bcell.seurat), levels = rev(levels(Idents(Bcell.seurat))))

DotPlot(Bcell.seurat, features = unique(top5_genes_Bcells$gene), assay = "RNA") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

ggsave("/Figures/Marker_genes_Bcells_flip.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, width = 9, height = 4, units = "in", compression = "lzw")

## Myeloische Zellen
myeloid.seurat <- RenameIdents(myeloid.seurat, 'M2 Macrophages_1' = 'M2 tissue-resident', 'M2 Macrophages_2' = 'TREM2-like Macrophages')
Idents(myeloid.seurat) <- factor(Idents(myeloid.seurat), 
                            levels = c("Inflammatory monocyte-derived Macrophages", "M1 Macrophages", "M2 tissue-resident", 
                                       "TREM2-like Macrophages", "cDC1", "cDC2", "Neutrophils"))
                              
Markers.Myeloid <- FindAllMarkers(myeloid.seurat, logfc.threshold = 0.25, min.pct = 0.1, only.pos = T)

top5_genes_Myeloid <- Markers.Myeloid %>% group_by(cluster) %>% dplyr::filter(avg_log2FC > 1) %>%
  slice_head(n = 5) %>% ungroup()

DotPlot(myeloid.seurat, features = unique(top5_genes_Myeloid$gene), 
        assay = "SCT") + coord_flip() + scale_y_discrete(labels = c("Inflam. monocyte- \n derived Macrophages", "M1 Macrophages", 
        "M2 tissue-resident", "TREM2-like Macrophages", "cDC1", "cDC2", "Neutrophils")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("/Figures/Marker_genes_Myeloid.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, height = 9, width = 7, units = "in", compression = "lzw")

## Custom Markers 
Myeloid_markers <- c("CD14", "LYZ", "CTSS", "CTSB", "B2M", "SIRPA", "PYCARD", "LILRB1", "VCAN", "IRF5", "NOS2", "CD163L1", "CD209", "C1QA",
                     "STAB1", "MAF", "TGFB1", "MERTK", "IGF1", "FCN1", "S100A8", "S100A9", "NLRP3", "FCGR3B", "TNF", "IL1B", "CXCL1", "HIF1A",
                     "PRDX1", "AIF1",  "C1QB", "C1QC", "TREM2", "CCL24", "APOE", "LIPA", "CD68", "CLEC9A", "IDO1", "IRF4", "CD1C", "FCER1A",
                     "CCR7", "FLT3", "LAMP3", "TNFSF14", "ALOX5AP", "SOD2", "CSF3R", "CXCL8", "FPR2", "TNFAIP6")

DotPlot(myeloid.seurat, features = unique(Myeloid_markers), assay = "SCT") + coord_flip() + 
  scale_y_discrete(labels = c("Inflam. monocyte- \n derived Macrophages", "M1 Macrophages",
        "M2 tissue-resident", "TREM2-like Macrophages", "cDC1", "cDC2", "Neutrophils")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("/Figures/Marker_genes_Myeloid_custom.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, height = 14, width = 9, units = "in", compression = "lzw")

## Heatmap
pseudo_Myeloid <- AggregateExpression(myeloid.seurat, assays = "RNA", return.seurat = T,
                                     group.by = "ident")

pseudo_Myeloid <- ScaleData(pseudo_Myeloid, features = unique(top5_genes_Myeloid$gene))
Marker_gene_rows <- which(rownames(pseudo_Myeloid@assays$RNA$scale.data) %in% unique(top5_genes_Myeloid$gene))
Marker_genes <- pseudo_Myeloid@assays$RNA$scale.data[Marker_gene_rows,]
custom_col_labels <- c("Inflam. monocyte- \n derived Macrophages", "M1 Macrophages",
        "M2 tissue-resident", "TREM2-like Macrophages", "cDC1", "cDC2", "Neutrophils")
png("/Figures/Marker_genes_Myeloid_heatmap.tiff", width = 1000,
    height = 1800, res = 150)
pheatmap(Marker_genes, main = "Gene expression \n(scaled z-score per gene)", cluster_cols = F, angle_col = 45, labels_col = custom_col_labels)
dev.off()

png("/Figures/Marker_genes_Myeloid_heatmap_viridis.tiff",
    width = 1000, height = 1800, res = 150)
pheatmap(Marker_genes, main = "Gene expression \n(scaled z-score per gene)", cluster_cols = F, angle_col = 45, labels_col = custom_col_labels,
         color = viridis(100))
dev.off()

## Heatmap flipped 
Marker_genes_flip <- t(Marker_genes)

png("/Figures/Marker_genes_Myeloid_heatmap_flipped.tiff", width = 1800,
    height = 1000, res = 150)
pheatmap(Marker_genes_flip, main = "Gene expression \n(scaled z-score per gene)", cluster_rows = F, angle_col = 45, treeheight_col = 0,
        cellwidth = 17, cellheight = 24, labels_row = custom_col_labels)
dev.off()

png("/Figures/Marker_genes_Myeloid_heatmap_viridis_flipped.tiff",
    width = 1800, height = 1000, res = 150)
pheatmap(Marker_genes_flip, main = "Gene expression \n(scaled z-score per gene)", cluster_rows = F, angle_col = 45, treeheight_col = 0,
         cellwidth = 17, cellheight = 24, labels_row = custom_col_labels, color = viridis(100))
dev.off()

## Custom marker genes Heatmap
pseudo_Myeloid <- ScaleData(pseudo_Myeloid, features = Myeloid_markers)
Marker_gene_rows <- which(rownames(pseudo_Myeloid@assays$RNA$scale.data) %in% unique(Myeloid_markers))
Marker_genes <- pseudo_Myeloid@assays$RNA$scale.data[Marker_gene_rows,]

png("/Figures/Marker_genes_Myeloid_custom_heatmap.tiff", width = 1000,
    height = 1800, res = 150)
pheatmap(Marker_genes, main = "Gene expression \n(scaled z-score per gene)", cluster_cols = F, angle_col = 45, labels_col = custom_col_labels)
dev.off()

png("/Figures/Marker_genes_Myeloid_custom_heatmap_viridis.tiff",
    width = 1000, height = 1800, res = 150)
pheatmap(Marker_genes, main = "Gene expression \n(scaled z-score per gene)", cluster_cols = F, angle_col = 45, 
         labels_col = custom_col_labels,color = viridis(100))
dev.off()

## Heatmap custom marker genes new flipped 
Marker_genes_flip <- t(Marker_genes)

png("/Figures/Marker_genes_Myeloid_custom_heatmap_flipped.tiff", width = 2200,
    height = 800, res = 150)
pheatmap(Marker_genes_flip, main = "Gene expression \n(scaled z-score per gene)", cluster_rows = F, angle_col = 45, treeheight_col = 0,
        cellwidth = 17, cellheight = 24, labels_row = custom_col_labels)
dev.off()

png("/Figures/Marker_genes_Myeloid_custom_heatmap_viridis_flipped.tiff",
    width = 2200, height = 800, res = 150)
pheatmap(Marker_genes_flip, main = "Gene expression \n(scaled z-score per gene)", cluster_rows = F, angle_col = 45, treeheight_col = 0,
         cellwidth = 17, cellheight = 24, labels_row = custom_col_labels, color = viridis(100))
dev.off()

## Flipped Dotplot Myeloid Cells
Idents(myeloid.seurat) <- factor(Idents(myeloid.seurat), levels = rev(levels(Idents(myeloid.seurat))))

DotPlot(myeloid.seurat, features = unique(top5_genes_Myeloid$gene), assay = "SCT") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

ggsave("/Figures/Marker_genes_Myeloid_flip.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, width = 12, height = 4, units = "in", compression = "lzw")


## Epithelzellen
epithelial.seurat <- readRDS("Epithelial_Cells_annotated.rds")

epithelial.seurat <- RenameIdents(epithelial.seurat, 
                                  'Enterocytes_1' = 'Mature Enterocytes', 'Enterocytes_2' = 'Enterocytes (early differentiated)', 
                                'Inflammatory Epithelial' = 'Intestinal Stem cells', 'Cycling Epithelial' = 'Cycling Transit Amplifying', 
                                'Basal Cells' = 'Enterocytes', 'Immature Enterocytes' = 'Activated/regenerative Enterocytes', 
                                'Stromal Cells' = 'Undefined')

Idents(epithelial.seurat) <- factor(Idents(epithelial.seurat), 
                            levels = c("Goblet Cells", "Mature Enterocytes", "Enterocytes (early differentiated)", 
                                       "Intestinal Stem cells", "Cycling Transit Amplifying", "Enterocytes", 
                                       "Activated/regenerative Enterocytes", "Undefined", "Enteroendocrine", "BEST4+ Enterocytes"))

Markers.epithelial <- FindAllMarkers(epithelial.seurat, logfc.threshold = 0.25, min.pct = 0.1, only.pos = T)

top5_genes_epithelial <- Markers.epithelial %>% group_by(cluster) %>% dplyr::filter(avg_log2FC > 1) %>%
  slice_head(n = 5) %>% ungroup()

DotPlot(epithelial.seurat, features = unique(top5_genes_epithelial$gene), 
        assay = "SCT") + coord_flip() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("/Figures/Marker_genes_epithelial.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, height = 9, width = 7, units = "in", compression = "lzw")

Idents(epithelial.seurat) <- factor(Idents(epithelial.seurat), levels = rev(levels(Idents(epithelial.seurat))))

DotPlot(epithelial.seurat, features = unique(top5_genes_epithelial$gene), assay = "SCT") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

ggsave("/Figures/Marker_genes_epithelial_flip.tiff", 
       plot = last_plot(), device = "tiff", dpi = 300, width = 12, height = 5, units = "in", compression = "lzw")

# Heatmap für Epithelzellen Markergene 
Idents(epithelial.seurat) <- factor(Idents(epithelial.seurat), levels = rev(levels(Idents(epithelial.seurat))))
pseudo_epithelial <- AggregateExpression(epithelial.seurat, assays = "RNA", return.seurat = T,
                                     group.by = "ident")

pseudo_epithelial <- ScaleData(pseudo_epithelial, features = unique(top5_genes_epithelial$gene))
Marker_gene_rows <- which(rownames(pseudo_epithelial@assays$RNA$scale.data) %in% unique(top5_genes_epithelial$gene))
Marker_genes <- pseudo_epithelial@assays$RNA$scale.data[Marker_gene_rows,]

png("/Figures/Marker_genes_Epithelial_heatmap.tiff", width = 1000,
    height = 1800, res = 150)
pheatmap(Marker_genes, main = "Gene expression \n(scaled z-score per gene)", cluster_cols = F, angle_col = 45)
dev.off()

png("/Figures/Marker_genes_Epithelial_heatmap_viridis.tiff",
    width = 1000, height = 1800, res = 150)
pheatmap(Marker_genes, main = "Gene expression \n(scaled z-score per gene)", cluster_cols = F, angle_col = 45, color = viridis(100))
dev.off()

## Heatmap flipped 
Marker_genes_flip <- t(Marker_genes)

png("/Figures/Marker_genes_Epithelial_heatmap_flipped.tiff", width = 2200,
    height = 1000, res = 150)
pheatmap(Marker_genes_flip, main = "Gene expression \n(scaled z-score per gene)", cluster_rows = F, angle_col = 45, treeheight_col = 0,
        cellwidth = 16, cellheight = 24)
dev.off()

png("/Figures/Marker_genes_Epithelial_heatmap_viridis_flipped.tiff",
    width = 2200, height = 1000, res = 150)
pheatmap(Marker_genes_flip, main = "Gene expression \n(scaled z-score per gene)", cluster_rows = F, angle_col = 45, treeheight_col = 0,
         cellwidth = 16, cellheight = 24, color = viridis(100))
dev.off()
```
